language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: knpw7zbBTdoIQFEte61d+ObKZSxDiKkNwdD9RaXlgRRoztmm+NDltDk5DgjYgZG86xyHJ29KXczxSGkIlC/SAd36hd/7HLnzYMkcjhjWwVbyk4HmTZFAL5haNVtrbgWvyvnNJjmaxGUsttag2p90CX+UeMXUs3Bsbzl7GViVpgCvOmIYcpD6ha016kSBfcexY0CuyLeBv/dUV7jp9LQKZHlnOBh3gk2UKMnJPOixYmD5JycbM1iGHgr0a/gu3TWIfioDD+P3oSJeaUCw0wnv1r1oSTxd6lE2qNZg/6AjJ0XotJwbxivffNm0qRmEqn1ukgIrlQxVmeFoAdrBafF+PME1ts607U8xBQQ1E+fqxbF/3f+gigf3C5R9wtUdQbnkoqv4xgEog13uvGS/58mF7Lm1j0Nka1IUToyilQHSkNGdPYBfOFTOwUFJxHSZXgwN/KiLVeutdRnhpSfZ7D+1KPN78Gz0sr3vBse5LnjzCeWyEnk0QjsoDrOMsTNeiALgbz8COBbkjFi3xIDJ7TkFxDV8Lsug/vk6OU1Sg9B+/e1YBw73x67lJnjk6ti9/PGyrCcR4muttUCngBfgqb4r52jLEB4wcMCCouFJwmT7Sq7Hm7Kn06o67+RJ6DE/3rjWiPakhgjsiT5VOIeiwyMTPF9lD8yZ9BbNnOXJ0VjrUMc=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
