language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: C/QGgkwb0Ir5FlCl0GDfXbomS2rVYCLWEBlrbCb5CtODM3GEwso1yBZT62Ex8qKJtxVbLKWTiGzcRBp4BpmdeeibYcO8D4ayVEWzGbfU0ryg0LrqWGYqut+qVA3Mh9bC/arIv0xApcOauPXcg7oHWJemtQeu4024ufH2tpenzBo4I91y/9eAOUTvhxufu3ClhKHKUE5c8KAoqln62Ex+CsEEIccjhQAMutaoNq+nZEQuz9QYFbHLjeuvP0t230F6CRjHeDnNXSG+AV9jDOWTZPT6l+qk1PnJ3JnhMZVctpexYhqEkKLqT5C+6BgQmLUkr3lGpjfedwbGFt3cZag117YTdC30nfFbPUx7HjeDWnWLyeFZBmSxgGOP0hnz/hQvEMu2Hxqp5vQHBpcA2Tx6bq4ijrHymv0BwkaM02s4QtIiPfXGezaCabkuxa1YGDgnRreyfVGVNUeBJmm68dJn/ibybnYPXG4Aj5FIzJkCJCTQYWDxcMJieW1GVzkoW7OLMoYpV0WBBsnN277QI51AVMILEE/NWtMD/op94ULuNQgnGVkHgMKenfN1Y/ZIrRyxmbwEbdvhcc24/d4R1UnhgEWFN2TI20BLnRu/lEVvb56R0bQ+K4RjhJMAneaJSB2XAvd7Lj1hyJ2JQK93Gj5460xm7reY0bSk+kqyDkJhN6o=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
